version: "1"

services:
  - type: web
    name: eticaret-backend
    runtime: node
    repo: https://github.com/volkan0x/eticaret-backend
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeployTrigger: commit
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: eticaret-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: eticaret-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: STORE_CORS
        sync: false
      - key: ADMIN_CORS
        sync: false
      - key: AUTH_CORS
        sync: false

  - type: redis
    name: eticaret-redis
    region: oregon
    plan: free
    ipAllowList: []

databases:
  - name: eticaret-db
    region: oregon
    plan: free
    databaseName: medusa_v2
    user: medusa
