# Exported from Render on 2026-03-20T10:35:05Z
version: "1"
services:
- type: web
  name: eticaret-backend
  runtime: node
  repo: https://github.com/volkan0x/eticaret-backend
  plan: free
  envVars:
  - key: DB_NAME
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: COOKIE_SECRET
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: REDIS_URL
    sync: false
  - key: AUTH_CORS
    sync: false
  - key: ADMIN_CORS
    sync: false
  - key: STORE_CORS
    sync: false
  region: oregon
  buildCommand: npm install; npm run build
  startCommand: npm run start
  autoDeployTrigger: commit
